### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### GitHub Corrected URLs 
Was | Now 
--- | --- 
https://github.com/geeeeeeeeek/wechat-electron/releases | https://github.com/geeeeeeeeek/electronic-wechat/releases 

### Other Corrected URLs 
Was | Now 
--- | --- 
http://npmjs.com | https://www.npmjs.com/

### CODE REVIEW

**Comment by geeeeeeeeek** [comment]
@ReadmeCritic So you are telling me you are a robot?!

**Comment by ReadmeCritic** [comment]
uh what

**Comment by geeeeeeeeek** [comment]
@ReadmeCritic Just got confused. I thought you are a bot that automatically checks everyone's repo.

**Comment by ReadmeCritic** [comment]
nah man you were carefully selected for url inaccuracy 🤓

**Comment by ReadmeCritic** [comment]
thanks for merging

**Pull request merged**
